#!/bin/bash
set -x
export HOME=/root
export LOGNAME=root
export TERM=vt100
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export ENV="HOME=$HOME LOGNAME=$LOGNAME TERM=$TERM PATH=$PATH"

IP=""
MAC=""
AFFINITY=""
ARGS=""

echo "$@"

ARGS_IN_PROGRESS=0
for var in $@; do
	if [[ $ARGS_IN_PROGRESS -eq 1 ]]; then
		case "$var" in
			IP=*|MAC=*|AFFINITY=*)
				ARGS_IN_PROGRESS=0
				# fall through to normal parsing for the next token
				;;
			*)
				if [[ -z "$ARGS" ]]; then
					ARGS="$var"
				else
					ARGS="$ARGS $var"
				fi
				continue
				;;
		esac
	fi

	case $var in
	IP=*)
		IP="${var#IP=}"
		;;

	MAC=*)
		MAC="${var#MAC=}"
		;;

	AFFINITY=*)
		AFFINITY="${var#AFFINITY=}"
		if [[ ${AFFINITY} != 1 ]] ; then
			AFFINITY=""
		fi
		;;
	ARGS=*)
		ARGS="${var#ARGS=}"
		ARGS_IN_PROGRESS=1
		;;
	esac
done

# strip matching surrounding quotes from ARGS so it can be re-split by the shell
if [[ "${ARGS:0:1}" == '"' && "${ARGS: -1}" == '"' ]]; then
	ARGS="${ARGS:1:${#ARGS}-2}"
fi
if [[ "${ARGS:0:1}" == "'" && "${ARGS: -1}" == "'" ]]; then
	ARGS="${ARGS:1:${#ARGS}-2}"
fi

# setup standard file system view
mkdir -p /run
mount -t proc /proc /proc
mount -t sysfs /sys /sys

# take care of /dev 1) try using devtmpfs and devpts or 2) dev of exiting fs and devpts
if ! mount -t devtmpfs -o mode=0755 udev /dev; then
  # failed to mount devtmpfs
  # so add a few useful things if not already in file system
  echo "W: devtmpfs not available, falling back to tmpfs for /dev"
  [[ -e /dev/console ]] || mknod -m 0600 /dev/console c 5 1
  [[ -e /dev/null ]] || mknod /dev/null c 1 3
  [[ -e /dev/zero ]] || mknod /dev/zero c 1 5
  [[ -e /dev/random ]] || mknod /dev/random c 1 8
  [[ -e /dev/urandom ]] || mknod /dev/urandom c 1 9
fi

[[ -e /dev/pts ]] || mkdir /dev/pts
mount -t devpts devpts /dev/pts

# Some things don't work properly without /etc/mtab.
ln -sf /proc/mounts /etc/mtab

# Start udev to load modules for hardware
/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never

lspci -knnd ::0200 | grep "Kernel modules" | while read -r line ; do
	entry=$(echo "${line}" | cut -d ":" -f 2)
	modprobe ${entry}
done

sleep 2

# Ensure that all found devices have drivers loaded
udevadm trigger
udevadm settle

# Print cmdline
echo "CMDLINE" >> /log
cat /proc/cmdline >> /log

ulimit -n 200000

# Running experimental setup scripts
echo "Running Setup scripts" >> /log
./exp/disable_ht.sh >> /log
./exp/turbo-boost.sh disable >> /log
echo "Done" >> /log

# Configure the requested network interface by MAC($2) to use IP($1)
if [ -n "${IP}" ]; then
	if [ -n "${MAC}" ]; then
		INF=`/usr/bin/ip -o link | awk -F ': ' -vIGNORECASE=1 '!/link\/ieee802\.11/ && /'"$MAC"'/ { print $2 }'`
	else
		INF="eth0"
	fi
	/usr/bin/ip address flush dev $INF
	/usr/bin/ip address add $IP/24 brd + dev $INF
	/usr/bin/ip link set $INF up

	if [ -n "${AFFINITY}" ]; then
		# Receive queue affinity has been requested, we will try and create a receive queue per CPU and
		# bind each one to a single CPU to preserve data locality
		CPU_CNT=$(nproc)
		/usr/sbin/ethtool -L ${INF} rx ${CPU_CNT} tx ${CPU_CNT}

		PCI_ADDR=$(basename $(readlink /sys/class/net/${INF}/device))
		CPU_IDX=0
		grep ${PCI_ADDR} /proc/interrupts | while read -r line; do
			IRQ=$(echo $line | cut -d ':' -f1)
			echo "${CPU_IDX}" > /proc/irq/${IRQ}/smp_affinity_list
			((CPU_IDX++))
			if (( CPU_IDX >= CPU_CNT )); then
				CPU_IDX=0
			fi
		done
	fi
fi

/usr/bin/ip address

# Run sshd
/usr/sbin/dropbear -E -R -p 22

sleep 5

echo "UPCALL BOOTED"

/bin/bash

