FROM debian:13

RUN apt-get update
RUN apt-get -y install bash sed libelf-dev bc hostname perl dropbear dropbear-bin dropbear-initramfs \
        pciutils msr-tools wget bzip2 curl xz-utils cpio passwd procps iproute2 \
	net-tools openssh-server openssh-sftp-server less ethtool libacl1 kmod libbabeltrace1 \
	libdebuginfod1t64 libnuma1 libpfm4 libpython3.13 libslang2 libtraceevent1 kmod
